include ../Makefile.inc

#DIRS = coffee

all:
	# $(ECHO) build in ./src
	# for d in $(DIRS); do (cd $$d; $(MAKE) $(MFLAGS)); done

clean:
	# $(ECHO) cleaning up in ./src
	# for d in $(DIRS); do (cd $$d; $(MAKE) clean ); done
